### ISSUE TITLE
Expose a way to set the Constants.SERVER_ADDR annotation

### ISSUE THREAD

**Issue by jakerobb** [openzipkin/brave-opentracing#39] opened 2017-04-28 20:55 UTC
I was instrumenting a Kafka producer today in my OT-instrumented, Brave+Zipkin-backed application, and had to write the following code:
```
span = tracer.buildSpan("produce to " + topic)
             .asChildOf(parentSpan)
             .withTag(Tags.SPAN_KIND.getKey(), Tags.SPAN_KIND_PRODUCER)
             .withTag(Tags.MESSAGE_BUS_DESTINATION.getKey(), topic)
             .withTag("key", key.toString())
             .withTag(Tags.PEER_SERVICE.getKey(), "kafka")
             .start();
if (span instanceof BraveSpan) {
    BraveSpan braveOpenTracingSpan = (BraveSpan) span;
    brave.Span nativeBraveSpan = braveOpenTracingSpan.unwrap();
    nativeBraveSpan.remoteEndpoint(KAFKA_ENDPOINT);
    // kind has to be CLIENT in order for Brave to set the "sa" based on the endpoint
    nativeBraveSpan.kind(Kind.CLIENT);
}
```

Without manipulating the native brave.Span, Zipkin does not render a service name for this span (see https://gist.github.com/jakerobb/d338a17138612f28aef295b0109fd567). It knows which service called it, and that's evident by the structure of the trace and in several places in the span's popup, but it leaves the span service name empty.

I think that BraveSpan should carry around an Endpoint.Builder, updating it whenever the `peer.*` tags are set, and it should build that and pass it to `brave.Span.remoteEndpoint(...)` it before invoking `finish()` on the brave.Span.

I think it should also set the brave.Span's `kind` to `Kind.CLIENT` when the `span.kind` tag is set to "producer" or "consumer".

Per @devinsba (https://gitter.im/openzipkin/zipkin?at=59038d6512d2409935aa7068):
> I’m not sure what the effect would be if we attached them on a span that also got ss/sr attached by the server though

That warrants some attention and unit tests, which may or may not already exist (possibly in Zipkin? I'm not sure where those precedence rules are applied) to ensure desired behavior.

**Comment by adriancole** [comment] 2017-04-29 00:59
Ok didnt notice the new producer consumer tags (such was considered here
but wasnt worth rippling everywhere as the action to take on a span is
scarcely different client vs producer, and who knows if the other side will
consider themselves a server or consumer!)

Thx for the notes

**Comment by adriancole** [comment] 2017-04-29 02:50
dupe of #37

**Closed by adriancole** 2017-04-29 02:50 UTC
